export const yearEvents: Record<number, { event: string; culture: string }> = {
  1940: { event: "Winston Churchill became Prime Minister of the UK", culture: "Pinocchio premiered in cinemas" },
  1941: { event: "Attack on Pearl Harbor drew the US into WWII", culture: "Citizen Kane was released" },
  1942: { event: "Battle of Midway turned the tide in the Pacific", culture: "Casablanca hit the silver screen" },
  1943: { event: "Italy surrendered to the Allied forces", culture: "Oklahoma! opened on Broadway" },
  1944: { event: "D-Day: Allied forces landed on Normandy beaches", culture: "Meet Me in St. Louis was released" },
  1945: { event: "World War II ended with the surrender of Japan", culture: "George Orwell published Animal Farm" },
  1946: { event: "The United Nations held its first General Assembly", culture: "It's a Wonderful Life premiered" },
  1947: { event: "India gained independence from Britain", culture: "The Diary of Anne Frank was published" },
  1948: { event: "The State of Israel was established", culture: "The Treasure of the Sierra Madre was released" },
  1949: { event: "NATO was founded", culture: "George Orwell published 1984" },
  1950: { event: "Korean War began", culture: "Cinderella was released by Disney" },
  1951: { event: "First color TV broadcasts began in the US", culture: "The Catcher in the Rye was published" },
  1952: { event: "Queen Elizabeth II ascended to the throne", culture: "Singin' in the Rain hit cinemas" },
  1953: { event: "Edmund Hillary and Tenzing Norgay summited Everest", culture: "The first James Bond novel was published" },
  1954: { event: "Brown v. Board of Education ended school segregation", culture: "Tolkien published The Lord of the Rings" },
  1955: { event: "Rosa Parks refused to give up her bus seat", culture: "Disneyland opened in California" },
  1956: { event: "The Suez Crisis unfolded", culture: "Elvis Presley released Heartbreak Hotel" },
  1957: { event: "The Soviet Union launched Sputnik into orbit", culture: "West Side Story opened on Broadway" },
  1958: { event: "NASA was established", culture: "The Hula Hoop became a craze" },
  1959: { event: "The Cuban Revolution brought Fidel Castro to power", culture: "Ben-Hur dominated the Oscars" },
  1960: { event: "John F. Kennedy was elected President", culture: "The Flintstones debuted on TV" },
  1961: { event: "Yuri Gagarin became the first human in space", culture: "West Side Story the film was released" },
  1962: { event: "The Cuban Missile Crisis brought the world to the brink", culture: "Dr. No was the first James Bond film" },
  1963: { event: "Martin Luther King Jr. gave his 'I Have a Dream' speech", culture: "The Beatles released their first album" },
  1964: { event: "The Civil Rights Act was signed into law", culture: "Mary Poppins hit cinemas" },
  1965: { event: "The first US combat troops arrived in Vietnam", culture: "The Sound of Music was released" },
  1966: { event: "The Cultural Revolution began in China", culture: "Star Trek debuted on television" },
  1967: { event: "The Six-Day War reshaped the Middle East", culture: "The Beatles released Sgt. Pepper's" },
  1968: { event: "Martin Luther King Jr. and Robert F. Kennedy were assassinated", culture: "2001: A Space Odyssey was released" },
  1969: { event: "Neil Armstrong walked on the Moon", culture: "Woodstock music festival took place" },
  1970: { event: "The first Earth Day was celebrated", culture: "The Beatles officially broke up" },
  1971: { event: "The microprocessor was invented", culture: "Willy Wonka & the Chocolate Factory was released" },
  1972: { event: "The Watergate scandal began", culture: "The Godfather premiered" },
  1973: { event: "The oil crisis shocked the world economy", culture: "Pink Floyd released The Dark Side of the Moon" },
  1974: { event: "President Nixon resigned from office", culture: "ABBA won Eurovision with Waterloo" },
  1975: { event: "The Vietnam War ended with the fall of Saigon", culture: "Jaws created the summer blockbuster" },
  1976: { event: "Apple Computer was founded", culture: "Rocky hit cinemas" },
  1977: { event: "The Voyager spacecraft were launched", culture: "Star Wars premiered and changed cinema forever" },
  1978: { event: "The first test-tube baby was born", culture: "Grease was the word in cinemas" },
  1979: { event: "The Iranian Revolution transformed the Middle East", culture: "Walkman portable music players were introduced" },
  1980: { event: "CNN launched as the first 24-hour news network", culture: "Pac-Man fever swept the world" },
  1981: { event: "The first Space Shuttle launched", culture: "MTV began broadcasting" },
  1982: { event: "The Falklands War took place", culture: "E.T. the Extra-Terrestrial was released" },
  1983: { event: "The internet adopted TCP/IP protocol", culture: "Return of the Jedi concluded the original Star Wars trilogy" },
  1984: { event: "The Macintosh computer was unveiled", culture: "Ghostbusters was a smash hit" },
  1985: { event: "Live Aid concerts raised money for famine relief", culture: "Back to the Future hit cinemas" },
  1986: { event: "The Chernobyl nuclear disaster occurred", culture: "Top Gun dominated the box office" },
  1987: { event: "The first Intifada began in Palestine", culture: "The Simpsons appeared as shorts on TV" },
  1988: { event: "The Pan Am 103 bombing shocked the world", culture: "Rain Man won Best Picture" },
  1989: { event: "The Berlin Wall fell, ending the Cold War era", culture: "The Game Boy launched worldwide" },
  1990: { event: "German reunification made history", culture: "Home Alone was the box office sensation" },
  1991: { event: "The World Wide Web went public", culture: "Nirvana released Nevermind" },
  1992: { event: "The European Union was established", culture: "Aladdin was a Disney hit" },
  1993: { event: "The Oslo Accords were signed", culture: "Jurassic Park thrilled audiences" },
  1994: { event: "Nelson Mandela became President of South Africa", culture: "The Lion King roared into cinemas" },
  1995: { event: "The World Trade Organization was founded", culture: "Toy Story was the first fully CGI film" },
  1996: { event: "Dolly the sheep was cloned", culture: "The Spice Girls released Wannabe" },
  1997: { event: "Hong Kong was returned to China", culture: "Titanic became the highest-grossing film" },
  1998: { event: "The International Space Station began construction", culture: "Google was founded" },
  1999: { event: "The Euro currency was introduced", culture: "The Matrix redefined sci-fi cinema" },
  2000: { event: "The Human Genome Project completed its draft", culture: "The first camera phone was released" },
  2001: { event: "The September 11 attacks changed the world", culture: "The first Harry Potter film was released" },
  2002: { event: "The Euro banknotes entered circulation", culture: "Spider-Man swung into cinemas" },
  2003: { event: "The Human Genome Project was completed", culture: "Finding Nemo charmed audiences" },
  2004: { event: "Facebook was launched from a Harvard dorm room", culture: "The Incredibles was released" },
  2005: { event: "YouTube launched and changed media forever", culture: "Batman Begins rebooted the franchise" },
  2006: { event: "Twitter was launched", culture: "Wii sports brought gaming to everyone" },
  2007: { event: "The iPhone was unveiled by Steve Jobs", culture: "Harry Potter and the Deathly Hallows was published" },
  2008: { event: "The global financial crisis shook the world", culture: "The Dark Knight was a cultural phenomenon" },
  2009: { event: "Barack Obama was inaugurated as the 44th US President", culture: "Avatar became the highest-grossing film" },
  2010: { event: "The Arab Spring began across the Middle East", culture: "Instagram launched and changed social media" },
};

export interface CountryLifeExpectancy {
  name: string;
  expectancy: number;
}

export const countryLifeExpectancies: CountryLifeExpectancy[] = [
  { name: "Global Average", expectancy: 73.0 },
  { name: "Japan", expectancy: 84.3 },
  { name: "Australia", expectancy: 83.4 },
  { name: "Switzerland", expectancy: 83.4 },
  { name: "Italy", expectancy: 83.5 },
  { name: "Spain", expectancy: 83.5 },
  { name: "South Korea", expectancy: 83.5 },
  { name: "Norway", expectancy: 82.9 },
  { name: "France", expectancy: 82.5 },
  { name: "Sweden", expectancy: 82.4 },
  { name: "Canada", expectancy: 82.3 },
  { name: "Netherlands", expectancy: 82.3 },
  { name: "New Zealand", expectancy: 82.3 },
  { name: "UK", expectancy: 81.3 },
  { name: "Germany", expectancy: 81.1 },
  { name: "USA", expectancy: 78.9 },
  { name: "China", expectancy: 78.2 },
  { name: "UAE", expectancy: 78.0 },
  { name: "Turkey", expectancy: 77.7 },
  { name: "Saudi Arabia", expectancy: 76.4 },
  { name: "Brazil", expectancy: 75.9 },
  { name: "Mexico", expectancy: 75.1 },
  { name: "Vietnam", expectancy: 73.6 },
  { name: "Bangladesh", expectancy: 72.6 },
  { name: "Egypt", expectancy: 72.0 },
  { name: "Indonesia", expectancy: 71.7 },
  { name: "Philippines", expectancy: 71.2 },
  { name: "India", expectancy: 70.8 },
  { name: "Pakistan", expectancy: 67.3 },
  { name: "South Africa", expectancy: 64.9 },
  { name: "Nigeria", expectancy: 54.7 },
];
